# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cai/pb/msf/msg/svc/transmit.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from cai.pb.msf.msg.comm import comm_pb2 as cai_dot_pb_dot_msf_dot_msg_dot_comm_dot_comm__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!cai/pb/msf/msg/svc/transmit.proto\x12\x0bmsf.msg.svc\x1a\x1e\x63\x61i/pb/msf/msg/comm/comm.proto\"2\n\x0ePbMultiMsgItem\x12\x10\n\x08\x66ileName\x18\x01 \x01(\t\x12\x0e\n\x06\x62uffer\x18\x02 \x01(\x0c\"/\n\rPbMultiMsgNew\x12\x1e\n\x03msg\x18\x01 \x03(\x0b\x32\x11.msf.msg.comm.Msg\"e\n\x12PbMultiMsgTransmit\x12\x1e\n\x03msg\x18\x01 \x03(\x0b\x32\x11.msf.msg.comm.Msg\x12/\n\npbItemList\x18\x02 \x03(\x0b\x32\x1b.msf.msg.svc.PbMultiMsgItem')



_PBMULTIMSGITEM = DESCRIPTOR.message_types_by_name['PbMultiMsgItem']
_PBMULTIMSGNEW = DESCRIPTOR.message_types_by_name['PbMultiMsgNew']
_PBMULTIMSGTRANSMIT = DESCRIPTOR.message_types_by_name['PbMultiMsgTransmit']
PbMultiMsgItem = _reflection.GeneratedProtocolMessageType('PbMultiMsgItem', (_message.Message,), {
  'DESCRIPTOR' : _PBMULTIMSGITEM,
  '__module__' : 'cai.pb.msf.msg.svc.transmit_pb2'
  # @@protoc_insertion_point(class_scope:msf.msg.svc.PbMultiMsgItem)
  })
_sym_db.RegisterMessage(PbMultiMsgItem)

PbMultiMsgNew = _reflection.GeneratedProtocolMessageType('PbMultiMsgNew', (_message.Message,), {
  'DESCRIPTOR' : _PBMULTIMSGNEW,
  '__module__' : 'cai.pb.msf.msg.svc.transmit_pb2'
  # @@protoc_insertion_point(class_scope:msf.msg.svc.PbMultiMsgNew)
  })
_sym_db.RegisterMessage(PbMultiMsgNew)

PbMultiMsgTransmit = _reflection.GeneratedProtocolMessageType('PbMultiMsgTransmit', (_message.Message,), {
  'DESCRIPTOR' : _PBMULTIMSGTRANSMIT,
  '__module__' : 'cai.pb.msf.msg.svc.transmit_pb2'
  # @@protoc_insertion_point(class_scope:msf.msg.svc.PbMultiMsgTransmit)
  })
_sym_db.RegisterMessage(PbMultiMsgTransmit)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PBMULTIMSGITEM._serialized_start=82
  _PBMULTIMSGITEM._serialized_end=132
  _PBMULTIMSGNEW._serialized_start=134
  _PBMULTIMSGNEW._serialized_end=181
  _PBMULTIMSGTRANSMIT._serialized_start=183
  _PBMULTIMSGTRANSMIT._serialized_end=284
# @@protoc_insertion_point(module_scope)
