"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
from builtins import (
    bool,
    bytes,
    int,
)

from cai.pb.msf.msg.comm.comm_pb2 import (
    Msg,
)

from google.protobuf.descriptor import (
    Descriptor,
    FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message,
)

from typing import (
    Iterable,
    Optional,
    Text,
)

from typing_extensions import (
    Literal,
)


DESCRIPTOR: FileDescriptor

class PbMultiMsgItem(Message):
    DESCRIPTOR: Descriptor
    FILENAME_FIELD_NUMBER: int
    BUFFER_FIELD_NUMBER: int
    fileName: Text
    buffer: bytes
    def __init__(self,
        *,
        fileName: Optional[Text] = ...,
        buffer: Optional[bytes] = ...,
        ) -> None: ...
    def HasField(self, field_name: Literal["buffer",b"buffer","fileName",b"fileName"]) -> bool: ...
    def ClearField(self, field_name: Literal["buffer",b"buffer","fileName",b"fileName"]) -> None: ...

class PbMultiMsgNew(Message):
    DESCRIPTOR: Descriptor
    MSG_FIELD_NUMBER: int
    @property
    def msg(self) -> RepeatedCompositeFieldContainer[Msg]: ...
    def __init__(self,
        *,
        msg: Optional[Iterable[Msg]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: Literal["msg",b"msg"]) -> None: ...

class PbMultiMsgTransmit(Message):
    DESCRIPTOR: Descriptor
    MSG_FIELD_NUMBER: int
    PBITEMLIST_FIELD_NUMBER: int
    @property
    def msg(self) -> RepeatedCompositeFieldContainer[Msg]: ...
    @property
    def pbItemList(self) -> RepeatedCompositeFieldContainer[PbMultiMsgItem]: ...
    def __init__(self,
        *,
        msg: Optional[Iterable[Msg]] = ...,
        pbItemList: Optional[Iterable[PbMultiMsgItem]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: Literal["msg",b"msg","pbItemList",b"pbItemList"]) -> None: ...
