# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: onlinepush_trans.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16onlinepush_trans.proto\"5\n\x0f\x45xtGroupKeyInfo\x12\x11\n\tcurMaxSeq\x18\x01 \x01(\r\x12\x0f\n\x07\x63urTime\x18\x02 \x01(\x04\"\xf6\x01\n\tPbMsgInfo\x12\x0f\n\x07\x66romUin\x18\x01 \x01(\x04\x12\r\n\x05toUin\x18\x02 \x01(\x04\x12\x0c\n\x04type\x18\x03 \x01(\r\x12\x0f\n\x07subtype\x18\x04 \x01(\r\x12\x0b\n\x03seq\x18\x05 \x01(\r\x12\x0b\n\x03uid\x18\x06 \x01(\x04\x12\x0c\n\x04time\x18\x07 \x01(\r\x12\x13\n\x0brealMsgTime\x18\x08 \x01(\r\x12\x10\n\x08nickName\x18\t \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\n \x01(\x0c\x12\r\n\x05svrIp\x18\x0b \x01(\r\x12)\n\x0f\x65xtGroupKeyInfo\x18\x0c \x01(\x0b\x32\x10.ExtGroupKeyInfo\x12\x13\n\x0bgeneralFlag\x18\x11 \x01(\r')



_EXTGROUPKEYINFO = DESCRIPTOR.message_types_by_name['ExtGroupKeyInfo']
_PBMSGINFO = DESCRIPTOR.message_types_by_name['PbMsgInfo']
ExtGroupKeyInfo = _reflection.GeneratedProtocolMessageType('ExtGroupKeyInfo', (_message.Message,), {
  'DESCRIPTOR' : _EXTGROUPKEYINFO,
  '__module__' : 'onlinepush_trans_pb2'
  # @@protoc_insertion_point(class_scope:ExtGroupKeyInfo)
  })
_sym_db.RegisterMessage(ExtGroupKeyInfo)

PbMsgInfo = _reflection.GeneratedProtocolMessageType('PbMsgInfo', (_message.Message,), {
  'DESCRIPTOR' : _PBMSGINFO,
  '__module__' : 'onlinepush_trans_pb2'
  # @@protoc_insertion_point(class_scope:PbMsgInfo)
  })
_sym_db.RegisterMessage(PbMsgInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EXTGROUPKEYINFO._serialized_start=26
  _EXTGROUPKEYINFO._serialized_end=79
  _PBMSGINFO._serialized_start=82
  _PBMSGINFO._serialized_end=328
# @@protoc_insertion_point(module_scope)
