"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
from builtins import (
    bool,
    bytes,
    int,
)

from google.protobuf.descriptor import (
    Descriptor,
    FileDescriptor,
)

from google.protobuf.message import (
    Message,
)

from typing import (
    Optional,
    Text,
)

from typing_extensions import (
    Literal,
)


DESCRIPTOR: FileDescriptor

class CustomFaceExtPb(Message):
    DESCRIPTOR: Descriptor
    class AnimationImageShow(Message):
        DESCRIPTOR: Descriptor
        EFFECTID_FIELD_NUMBER: int
        ANIMATIONPARAM_FIELD_NUMBER: int
        effectId: int
        animationParam: bytes
        def __init__(self,
            *,
            effectId: Optional[int] = ...,
            animationParam: Optional[bytes] = ...,
            ) -> None: ...
        def HasField(self, field_name: Literal["animationParam",b"animationParam","effectId",b"effectId"]) -> bool: ...
        def ClearField(self, field_name: Literal["animationParam",b"animationParam","effectId",b"effectId"]) -> None: ...

    class ResvAttr(Message):
        DESCRIPTOR: Descriptor
        IMAGEBIZTYPE_FIELD_NUMBER: int
        CUSTOMFACETYPE_FIELD_NUMBER: int
        EMOJIPACKAGEID_FIELD_NUMBER: int
        EMOJIID_FIELD_NUMBER: int
        TEXT_FIELD_NUMBER: int
        DOUTUSUPPLIERS_FIELD_NUMBER: int
        IMAGESHOW_FIELD_NUMBER: int
        TEXTSUMMARY_FIELD_NUMBER: int
        EMOJIFROM_FIELD_NUMBER: int
        EMOJISOURCE_FIELD_NUMBER: int
        EMOJIWEBURL_FIELD_NUMBER: int
        EMOJIICONURL_FIELD_NUMBER: int
        EMOJIMARKETFACENAME_FIELD_NUMBER: int
        SOURCE_FIELD_NUMBER: int
        CAMERACAPTURETEMPLATEINFO_FIELD_NUMBER: int
        CAMERACAPTUREMATERIALNAME_FIELD_NUMBER: int
        ADEMOJUMPURL_FIELD_NUMBER: int
        ADEMODESCSTR_FIELD_NUMBER: int
        DOWNLOADINDEX_FIELD_NUMBER: int
        imageBizType: int
        customfaceType: int
        emojiPackageid: int
        emojiId: int
        text: Text
        doutuSuppliers: Text
        @property
        def imageShow(self) -> CustomFaceExtPb.AnimationImageShow: ...
        textSummary: bytes
        emojiFrom: int
        emojiSource: Text
        emojiWebUrl: Text
        emojiIconUrl: Text
        emojiMarketFaceName: Text
        source: int
        cameraCaptureTemplateinfo: Text
        cameraCaptureMaterialname: Text
        adEmoJumpUrl: Text
        adEmoDescStr: Text
        downloadIndex: bytes
        def __init__(self,
            *,
            imageBizType: Optional[int] = ...,
            customfaceType: Optional[int] = ...,
            emojiPackageid: Optional[int] = ...,
            emojiId: Optional[int] = ...,
            text: Optional[Text] = ...,
            doutuSuppliers: Optional[Text] = ...,
            imageShow: Optional[CustomFaceExtPb.AnimationImageShow] = ...,
            textSummary: Optional[bytes] = ...,
            emojiFrom: Optional[int] = ...,
            emojiSource: Optional[Text] = ...,
            emojiWebUrl: Optional[Text] = ...,
            emojiIconUrl: Optional[Text] = ...,
            emojiMarketFaceName: Optional[Text] = ...,
            source: Optional[int] = ...,
            cameraCaptureTemplateinfo: Optional[Text] = ...,
            cameraCaptureMaterialname: Optional[Text] = ...,
            adEmoJumpUrl: Optional[Text] = ...,
            adEmoDescStr: Optional[Text] = ...,
            downloadIndex: Optional[bytes] = ...,
            ) -> None: ...
        def HasField(self, field_name: Literal["adEmoDescStr",b"adEmoDescStr","adEmoJumpUrl",b"adEmoJumpUrl","cameraCaptureMaterialname",b"cameraCaptureMaterialname","cameraCaptureTemplateinfo",b"cameraCaptureTemplateinfo","customfaceType",b"customfaceType","doutuSuppliers",b"doutuSuppliers","downloadIndex",b"downloadIndex","emojiFrom",b"emojiFrom","emojiIconUrl",b"emojiIconUrl","emojiId",b"emojiId","emojiMarketFaceName",b"emojiMarketFaceName","emojiPackageid",b"emojiPackageid","emojiSource",b"emojiSource","emojiWebUrl",b"emojiWebUrl","imageBizType",b"imageBizType","imageShow",b"imageShow","source",b"source","text",b"text","textSummary",b"textSummary"]) -> bool: ...
        def ClearField(self, field_name: Literal["adEmoDescStr",b"adEmoDescStr","adEmoJumpUrl",b"adEmoJumpUrl","cameraCaptureMaterialname",b"cameraCaptureMaterialname","cameraCaptureTemplateinfo",b"cameraCaptureTemplateinfo","customfaceType",b"customfaceType","doutuSuppliers",b"doutuSuppliers","downloadIndex",b"downloadIndex","emojiFrom",b"emojiFrom","emojiIconUrl",b"emojiIconUrl","emojiId",b"emojiId","emojiMarketFaceName",b"emojiMarketFaceName","emojiPackageid",b"emojiPackageid","emojiSource",b"emojiSource","emojiWebUrl",b"emojiWebUrl","imageBizType",b"imageBizType","imageShow",b"imageShow","source",b"source","text",b"text","textSummary",b"textSummary"]) -> None: ...

    def __init__(self,
        ) -> None: ...
