# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cai/pb/im/msg/resv/custom_face.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$cai/pb/im/msg/resv/custom_face.proto\"\xb1\x04\n\x0f\x43ustomFaceExtPb\x1a>\n\x12\x41nimationImageShow\x12\x10\n\x08\x65\x66\x66\x65\x63tId\x18\x01 \x01(\x05\x12\x16\n\x0e\x61nimationParam\x18\x02 \x01(\x0c\x1a\xdd\x03\n\x08ResvAttr\x12\x14\n\x0cimageBizType\x18\x01 \x01(\r\x12\x16\n\x0e\x63ustomfaceType\x18\x02 \x01(\r\x12\x16\n\x0e\x65mojiPackageid\x18\x03 \x01(\r\x12\x0f\n\x07\x65mojiId\x18\x04 \x01(\r\x12\x0c\n\x04text\x18\x05 \x01(\t\x12\x16\n\x0e\x64outuSuppliers\x18\x06 \x01(\t\x12\x36\n\timageShow\x18\x07 \x01(\x0b\x32#.CustomFaceExtPb.AnimationImageShow\x12\x13\n\x0btextSummary\x18\t \x01(\x0c\x12\x11\n\temojiFrom\x18\n \x01(\r\x12\x13\n\x0b\x65mojiSource\x18\x0b \x01(\t\x12\x13\n\x0b\x65mojiWebUrl\x18\x0c \x01(\t\x12\x14\n\x0c\x65mojiIconUrl\x18\r \x01(\t\x12\x1b\n\x13\x65mojiMarketFaceName\x18\x0e \x01(\t\x12\x0e\n\x06source\x18\x0f \x01(\r\x12!\n\x19\x63\x61meraCaptureTemplateinfo\x18\x10 \x01(\t\x12!\n\x19\x63\x61meraCaptureMaterialname\x18\x11 \x01(\t\x12\x14\n\x0c\x61\x64\x45moJumpUrl\x18\x12 \x01(\t\x12\x14\n\x0c\x61\x64\x45moDescStr\x18\x13 \x01(\t\x12\x15\n\rdownloadIndex\x18\x14 \x01(\x0c')



_CUSTOMFACEEXTPB = DESCRIPTOR.message_types_by_name['CustomFaceExtPb']
_CUSTOMFACEEXTPB_ANIMATIONIMAGESHOW = _CUSTOMFACEEXTPB.nested_types_by_name['AnimationImageShow']
_CUSTOMFACEEXTPB_RESVATTR = _CUSTOMFACEEXTPB.nested_types_by_name['ResvAttr']
CustomFaceExtPb = _reflection.GeneratedProtocolMessageType('CustomFaceExtPb', (_message.Message,), {

  'AnimationImageShow' : _reflection.GeneratedProtocolMessageType('AnimationImageShow', (_message.Message,), {
    'DESCRIPTOR' : _CUSTOMFACEEXTPB_ANIMATIONIMAGESHOW,
    '__module__' : 'cai.pb.im.msg.resv.custom_face_pb2'
    # @@protoc_insertion_point(class_scope:CustomFaceExtPb.AnimationImageShow)
    })
  ,

  'ResvAttr' : _reflection.GeneratedProtocolMessageType('ResvAttr', (_message.Message,), {
    'DESCRIPTOR' : _CUSTOMFACEEXTPB_RESVATTR,
    '__module__' : 'cai.pb.im.msg.resv.custom_face_pb2'
    # @@protoc_insertion_point(class_scope:CustomFaceExtPb.ResvAttr)
    })
  ,
  'DESCRIPTOR' : _CUSTOMFACEEXTPB,
  '__module__' : 'cai.pb.im.msg.resv.custom_face_pb2'
  # @@protoc_insertion_point(class_scope:CustomFaceExtPb)
  })
_sym_db.RegisterMessage(CustomFaceExtPb)
_sym_db.RegisterMessage(CustomFaceExtPb.AnimationImageShow)
_sym_db.RegisterMessage(CustomFaceExtPb.ResvAttr)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CUSTOMFACEEXTPB._serialized_start=41
  _CUSTOMFACEEXTPB._serialized_end=602
  _CUSTOMFACEEXTPB_ANIMATIONIMAGESHOW._serialized_start=60
  _CUSTOMFACEEXTPB_ANIMATIONIMAGESHOW._serialized_end=122
  _CUSTOMFACEEXTPB_RESVATTR._serialized_start=125
  _CUSTOMFACEEXTPB_RESVATTR._serialized_end=602
# @@protoc_insertion_point(module_scope)
