# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cai/pb/im/msg/resv/not_online_image.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)cai/pb/im/msg/resv/not_online_image.proto\"\xa6\x03\n\x13NotOnlineImageExtPb\x1a\x8e\x03\n\x08ResvAttr\x12\x14\n\x0cimageBizType\x18\x01 \x01(\r\x12\x16\n\x0e\x63ustomfaceType\x18\x02 \x01(\r\x12\x16\n\x0e\x65mojiPackageid\x18\x03 \x01(\r\x12\x0f\n\x07\x65mojiId\x18\x04 \x01(\r\x12\x0c\n\x04text\x18\x05 \x01(\t\x12\x16\n\x0e\x64outuSuppliers\x18\x06 \x01(\t\x12\x13\n\x0btextSummary\x18\x08 \x01(\x0c\x12\x11\n\temojiFrom\x18\n \x01(\r\x12\x13\n\x0b\x65mojiSource\x18\x0b \x01(\t\x12\x13\n\x0b\x65mojiWebUrl\x18\x0c \x01(\t\x12\x14\n\x0c\x65mojiIconUrl\x18\r \x01(\t\x12\x1b\n\x13\x65mojiMarketFaceName\x18\x0e \x01(\t\x12\x0e\n\x06source\x18\x0f \x01(\r\x12!\n\x19\x63\x61meraCaptureTemplateinfo\x18\x10 \x01(\t\x12!\n\x19\x63\x61meraCaptureMaterialname\x18\x11 \x01(\t\x12\x14\n\x0c\x61\x64\x45moJumpUrl\x18\x12 \x01(\t\x12\x14\n\x0c\x61\x64\x45moDescStr\x18\x13 \x01(\t')



_NOTONLINEIMAGEEXTPB = DESCRIPTOR.message_types_by_name['NotOnlineImageExtPb']
_NOTONLINEIMAGEEXTPB_RESVATTR = _NOTONLINEIMAGEEXTPB.nested_types_by_name['ResvAttr']
NotOnlineImageExtPb = _reflection.GeneratedProtocolMessageType('NotOnlineImageExtPb', (_message.Message,), {

  'ResvAttr' : _reflection.GeneratedProtocolMessageType('ResvAttr', (_message.Message,), {
    'DESCRIPTOR' : _NOTONLINEIMAGEEXTPB_RESVATTR,
    '__module__' : 'cai.pb.im.msg.resv.not_online_image_pb2'
    # @@protoc_insertion_point(class_scope:NotOnlineImageExtPb.ResvAttr)
    })
  ,
  'DESCRIPTOR' : _NOTONLINEIMAGEEXTPB,
  '__module__' : 'cai.pb.im.msg.resv.not_online_image_pb2'
  # @@protoc_insertion_point(class_scope:NotOnlineImageExtPb)
  })
_sym_db.RegisterMessage(NotOnlineImageExtPb)
_sym_db.RegisterMessage(NotOnlineImageExtPb.ResvAttr)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NOTONLINEIMAGEEXTPB._serialized_start=46
  _NOTONLINEIMAGEEXTPB._serialized_end=468
  _NOTONLINEIMAGEEXTPB_RESVATTR._serialized_start=70
  _NOTONLINEIMAGEEXTPB_RESVATTR._serialized_end=468
# @@protoc_insertion_point(module_scope)
